schema_version = "1.0.0"

id = "bioxelnodes"
version = "1.0.2"
name = "Bioxel Nodes"
tagline = "For scientific volumetric data visualization in Blender"
maintainer = "Ma Nan <icrdr2010@outlook.com>"
type = "add-on"
website = "https://omoolab.github.io/BioxelNodes/latest"

tags = ["Geometry Nodes", "Render", "Import-Export"]
blender_version_min = "4.2.0"
license = ['SPDX:GPL-3.0-or-later']
copyright = ["2024 OmooLab"]
platforms = ["windows-x64", "linux-x64", "macos-arm64", "macos-x64"]

wheels = [
  "./wheels/SimpleITK-2.3.1-cp311-cp311-win_amd64.whl",
  "./wheels/SimpleITK-2.3.1-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/SimpleITK-2.3.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/SimpleITK-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/lxml-5.3.0-cp311-cp311-win_amd64.whl",
  "./wheels/lxml-5.3.0-cp311-cp311-macosx_10_9_arm64.whl",
  "./wheels/lxml-5.3.0-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/lxml-5.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/h5py-3.11.0-cp311-cp311-win_amd64.whl",
  "./wheels/h5py-3.11.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/h5py-3.11.0-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/h5py-3.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/tifffile-2024.7.24-py3-none-any.whl",
  "./wheels/pyometiff-1.0.0-py3-none-any.whl",
  "./wheels/mrcfile-1.5.1-py2.py3-none-any.whl",
  "./wheels/transforms3d-0.4.2-py3-none-any.whl"
]

[permissions]
files = "Import/export volume data from/to disk"